HW03v1/Controllers/authorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03v1.Models;

namespace HW03v1.Controllers
{
    public class authorsController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: authors
        public async Task<ActionResult> Index()
        {
            return View(await db.authors.ToListAsync());
        }

        // GET: authors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // GET: authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(authors);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(authors);
        }

        // GET: authors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authors).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(authors);
        }

        // GET: authors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            authors authors = await db.authors.FindAsync(id);
            db.authors.Remove(authors);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03v1/Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03v1.Models;

namespace HW03v1.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03v1/Controllers/borrowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03v1.Models;

namespace HW03v1.Controllers
{
    public class borrowsController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: borrows
        public async Task<ActionResult> Index()
        {
            var borrows = db.borrows.Include(b => b.books).Include(b => b.students);
            return View(await borrows.ToListAsync());
        }

        // GET: borrows/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // GET: borrows/Create
        public ActionResult Create()
        {
            ViewBag.bookId = new SelectList(db.books, "bookId", "name");
            ViewBag.studentId = new SelectList(db.students, "studentId", "name");
            return View();
        }

        // POST: borrows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.borrows.Add(borrows);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // POST: borrows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrows).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // POST: borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            borrows borrows = await db.borrows.FindAsync(id);
            db.borrows.Remove(borrows);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03v1/Controllers/typesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HW03v1.Models;

namespace HW03v1.Controllers
{
    public class typesController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: types
        public async Task<ActionResult> Index()
        {
            return View(await db.types.ToListAsync());
        }

        // GET: types/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // GET: types/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: types/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.types.Add(types);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(types);
        }

        // GET: types/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: types/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.Entry(types).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(types);
        }

        // GET: types/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            types types = await db.types.FindAsync(id);
            db.types.Remove(types);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HW03v1/Views/Home/About.cshtml
@model HW03v1.Models.CombinedViewModel

@{
    ViewBag.Title = "Maintain";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<div class="container">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Author  -->
    <p>
        <h1> Authors </h1><a href="#" class="create-link btn btn-primary" style="background-color: rebeccapurple" data-url="@Url.Action("Create", "authors")"> Create </a>
    </p>


    <table class="table table-bordered">
        <thead>
            <tr style="background-color: mediumpurple;">
                <th>@Html.DisplayNameFor(model => model.author.First().name)</th>
                <th>@Html.DisplayNameFor(model => model.author.First().surname)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.author)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.name)</td>
                    <td>@Html.DisplayFor(modelItem => item.surname)</td>
                    <td>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Edit", "authors", new { id = item.authorId })">Edit</a>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Details", "authors", new { id = item.authorId })">Details</a>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Delete", "authors", new { id = item.authorId })">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>


    <!-- Pagination Authors -->
    <!-- <ul class="pagination">
         @for (int i = 1; i <= ViewBag.TotalAuthorPages; i++)
         {
             <li class="page-item @(i == ViewBag.CurrentAuthorPage ? "active" : "")">
                 <a class="page-link" href="@Url.Action("About", new { authorPage = i })">@i</a>
             </li>
         }
     </ul>-->
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.TotalBorrowPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentBorrowsPage ? "active" : "")">
                // THIS WORD: CurrentBorrowsPage, otherwise your page list wont show
                <a class="page-link" href="@Url.Action("About", new { borrowPage = i })">@i</a>
            </li>
        }
    </ul>


    <!-- Types  -->
    <p>
        <h1> Types </h1><a href="#" class="create-link btn btn-primary" style="background-color: rebeccapurple" data-url="@Url.Action("Create", "types")"> Create </a>
    </p>


    <table class="table table-bordered">
        <thead>
            <tr style="background-color: mediumpurple;">
                <th>@Html.DisplayNameFor(model => model.type.First().name)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.type)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.name)</td>
                    <td>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Edit", "types", new { id = item.typeId })">Edit</a>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Details", "types", new { id = item.typeId })">Details</a>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Delete", "types", new { id = item.typeId })">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>


    <!-- Pagination Types -->
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.TotalTypesPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentTypesPage ? "active" : "")">
                <a class="page-link" href="@Url.Action("About", new { typesPage = i })">@i</a>
            </li>
        }
    </ul>

    <!-- Borrows -->
    <p>
        <h1> Borrows </h1> <a href="#" class="create-link btn btn-primary" style="background-color: rebeccapurple" data-url="@Url.Action("Create", "borrows")"> Create </a>
    </p>



    <table class="table table-bordered">
        <thead>
            <tr style="background-color: mediumpurple;">
                <th>@Html.DisplayNameFor(model => model.borrow.First().takenDate)</th>
                <th>@Html.DisplayNameFor(model => model.borrow.First().broughtDate)</th>
                <th>@Html.DisplayNameFor(model => model.borrow.First().books.name)</th>
                <th>@Html.DisplayNameFor(model => model.borrow.First().students.name)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.borrow)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.takenDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.broughtDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.books.name)</td>
                    <td>@Html.DisplayFor(modelItem => item.students.name)</td>
                    <td>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Edit", "types", new { id = item.borrowId })">Edit</a>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Details", "types", new { id = item.borrowId })">Details</a>
                        <a href="#" class="edit-link btn btn-info" style="background-color: rebeccapurple" data-url="@Url.Action("Delete", "types", new { id = item.borrowId })">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>



    <!-- Pagination Borrows -->
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.TotalBorrowsPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentBorrowsPage ? "active" : "")">
                <a class="page-link" href="@Url.Action("About", new { borrowPage = i })">@i</a>
            </li>
        }
    </ul>

    <hr />
</div>
































<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sample Async CRUD</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-content">
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {

        $(".edit-link, .edit-link-in-modal").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });


        $("#modal-content").on("submit", "form", function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr("action");
            var formData = form.serialize();

            $.post(url, formData, function (data) {
                $("#myModal").modal("hide");
                location.reload();
            });
        });


        $(".details-link, .delete-link, .create-link, .create-lookup-link").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });
    });
</script>

HW03v1/Views/Home/Index.cshtml
@model HW03v1.Models.CombinedViewModel

@{
    ViewBag.Title = "Combined Index";
}

<style>

</style>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<div class="container">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.0/dist/js/bootstrap.bundle.min.js"></script>

    <p>
        <h1> Students </h1>  <a href="#" class="create-link btn btn-primary" style="background-color: rebeccapurple" data-url="@Url.Action("Create", "students")"> Create </a> 
    </p>


    <table class="table table-bordered">
        <thead>
            <tr style="background-color:mediumpurple;">
                <th>@Html.DisplayNameFor(model => model.student.First().name)</th>
                <th>@Html.DisplayNameFor(model => model.student.First().surname)</th>
                <th>@Html.DisplayNameFor(model => model.student.First().birthdate)</th>
                <th>@Html.DisplayNameFor(model => model.student.First().gender)</th>
                <th>@Html.DisplayNameFor(model => model.student.First().@class)</th>
                <th>@Html.DisplayNameFor(model => model.student.First().point)</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.student)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.name)</td>
                    <td>@Html.DisplayFor(modelItem => item.surname)</td>
                    <td>@Html.DisplayFor(modelItem => item.birthdate)</td>
                    <td>@Html.DisplayFor(modelItem => item.gender)</td>
                    <td>@Html.DisplayFor(modelItem => item.@class)</td>
                    <td>@Html.DisplayFor(modelItem => item.point)</td>


                </tr>
            }
        </tbody>
    </table>


    <!-- Pagination student -->
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.TotalStudentPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentStudentPage ? "active" : "")">
                <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
            </li>
        }
    </ul>



    <p>
        <h1> Books  </h1> <a href="#" class="create-link btn btn-primary" style="background-color: rebeccapurple" data-url="@Url.Action("Create", "books")"> Create </a> 
    </p>


    <table class="table table-bordered">
        <thead>
            <tr style="background-color: mediumpurple;">
                <th>@Html.DisplayNameFor(model => model.book.First().name)</th>
                <th>@Html.DisplayNameFor(model => model.book.First().pagecount)</th>
                <th>@Html.DisplayNameFor(model => model.book.First().point)</th>
                <th>@Html.DisplayNameFor(model => model.book.First().authors.name)</th>
                <th>@Html.DisplayNameFor(model => model.book.First().types.name)</th>
                @* <th>@Html.DisplayNameFor(model => model.book.First().borrows.) </th>*@

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.book)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.name)</td>
                    <td>@Html.DisplayFor(modelItem => item.pagecount)</td>
                    <td>@Html.DisplayFor(modelItem => item.point)</td>
                    <td>@Html.DisplayFor(modelItem => item.authors.name)</td>
                    <td>@Html.DisplayFor(modelItem => item.types.name)</td>
                    @*<td>@Html.DisplayFor(modelItem => item.borrows.)</td>*@


                </tr>
            }
        </tbody>
    </table>


    <!-- Pagination book -->
    <ul class="pagination">
        @for (int i = 1; i <= ViewBag.TotalBookPages; i++)
        {
            <li class="page-item @(i == ViewBag.CurrentBookPage ? "active" : "")">
                <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
            </li>
        }
    </ul>
    <hr />
</div>



<div id="myModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Sample Async CRUD</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-content">
            </div>
        </div>
    </div>
</div>


<script>
    $(function () {

        $(".edit-link, .edit-link-in-modal").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });


        $("#modal-content").on("submit", "form", function (e) {
            e.preventDefault();
            var form = $(this);
            var url = form.attr("action");
            var formData = form.serialize();

            $.post(url, formData, function (data) {
                $("#myModal").modal("hide");
                location.reload();
            });
        });


        $(".details-link, .delete-link, .create-link, .create-lookup-link").click(function (e) {
            e.preventDefault();
            var url = $(this).data("url");

            $.get(url, function (data) {
                $("#modal-content").empty();
                $("#modal-content").html(data);
                $("#myModal").modal("show");
            });
        });
    });
</script>